config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :blogposts
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'homepage#index'
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blogpost.rb
# frozen_string_literal: true

class Blogpost < ApplicationRecord
  validates :author, presence: true
  validates :title, presence: true
  validates :content, presence: true
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/blogposts_controller.rb
# frozen_string_literal: true

class BlogpostsController < ApplicationController
  before_action :set_blogpost, only: %i[show edit update destroy]

  def index
    @blogposts = Blogpost.paginate(page: params[:page], per_page: 3)
  end

  # GET
  def show; end

  def new
    @blogpost = Blogpost.new
  end

  def edit; end

  # POST /blogposts or /blogposts.json
  def create
    @blogpost = Blogpost.new(blogpost_params)

    respond_to do |format|
      if @blogpost.save
        format.html { redirect_to @blogpost, notice: 'Blogpost was successfully created.' }
        format.json { render :show, status: :created, location: @blogpost }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @blogpost.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /blogposts/1 or /blogposts/1.json
  def update
    respond_to do |format|
      if @blogpost.update(blogpost_params)
        format.html { redirect_to @blogpost, notice: 'Blogpost was successfully updated.' }
        format.json { render :show, status: :ok, location: @blogpost }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @blogpost.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /blogposts/1 or /blogposts/1.json
  def destroy
    @blogpost.destroy
    respond_to do |format|
      format.html { redirect_to blogposts_url, notice: 'Blogpost was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_blogpost
    @blogpost = Blogpost.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def blogpost_params
    params.require(:blogpost).permit(:author, :title, :content)
  end
end

app/controllers/homepage_controller.rb
# frozen_string_literal: true

class HomepageController < ApplicationController
  def index; end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
  class CodeRayify < Redcarpet::Render::HTML
    def block_code(code, language)
      CodeRay.scan(code, language).div unless language.nil?
    end
  end

  def markdown(text)
    renderer = CodeRayify.new(hard_wrap: true, filter_html: true, prettify: true)
    options = {
      autolink: true,
      no_intra_emphasis: true,
      disable_indented_code_blocks: true,
      fenced_code_blocks: true,
      strikethrough: true,
      highlight: true,
      superscript: true,
      footnotes: true,
      tables: true
    }
    Redcarpet::Markdown.new(renderer, options).render(text).html_safe # rubocop:disable Rails/OutputSafety
  end

  def malicious_markdown(text)
    renderer = Redcarpet::Render::HTML.new(hard_wrap: true)
    options = {
      autolink: true,
      no_intra_emphasis: true
    }
    Redcarpet::Markdown.new(renderer, options).render(text).html_safe
  end
end

app/helpers/blogposts_helper.rb
# frozen_string_literal: true

module BlogpostsHelper
end

app/helpers/homepage_helper.rb
# frozen_string_literal: true

module HomepageHelper
end

app/views/blogposts/_form.html.haml
= form_with(model: blogpost) do |form|
  - if blogpost.errors.any?
    #error_explanation
      %h2.error
        = pluralize(blogpost.errors.count, "Error")
        prohibited this blogpost from being saved:
      %ul
        - blogpost.errors.each do |error|
          %li.error= error.full_message
  %section.section
    .field
      = form.label :author
      = form.text_field :author, :style => "width: 30%"
  %section.section
    .field
      = form.label :title
      = form.text_field :title, :style => "width: 30%"
  %section.section
    .field
      = form.label :content
      = form.text_area :content, :style => "width: 90%; height: 50%"
  .actions
    = form.submit 'Save', class: "link green"

app/views/blogposts/edit.html.haml
%h1 Editing Blogpost
= render 'form', blogpost: @blogpost
= link_to 'Show', @blogpost, class: "link blue"
|
= link_to 'Back', blogposts_path, class: "link red"

app/views/blogposts/index.html.haml
%h1.heading Blogposts
= link_to 'New Blogpost', new_blogpost_path, class: "link blue"
= link_to 'Home', root_path, class: "link grey"

=will_paginate @blogposts

%table.section
  %thead
  %tbody.section--white
    - @blogposts.order(:title).each do |blogpost|
      %tr
        %td.author= "Author: \n #{blogpost.author}"
        %td= "Title: #{malicious_markdown(blogpost.title)}"
        %td.content= "Content: #{markdown(blogpost.content)}"
        %td.button= link_to 'Show', blogpost
        %td.button= link_to 'Edit', edit_blogpost_path(blogpost)
        %td.button= link_to 'Destroy', blogpost, method: :delete, data: { confirm: 'Are you sure?' }
%br/

app/views/blogposts/new.html.haml
%h1.heading New Blogpost
= render 'form', blogpost: @blogpost
= link_to 'Back', blogposts_path, class: "link red"

app/views/blogposts/show.html.haml
%div.section
  %strong Author:
  = @blogpost.author
%div.section
  %strong Title:
  = @blogpost.title
%div.section
  %strong Content:
  =markdown(@blogpost.content)
= link_to 'Edit', edit_blogpost_path(@blogpost), class: "link blue"
|
= link_to 'Back', blogposts_path, class: "link red"

app/views/homepage/index.html.haml
%h1.heading Welcome to SaVorum
%h2.heading An oasis on earth to chat and post information.

%section.section
    %h3 Blogposts
    %p This the safest blogforum on Earth for sharing and storing informatioN. Users receives the possibility to manage every post anonymously. Because we think our users can be trusted with the freedom we give them. 
    %div{ :style => "text-align: center;" } Drobo kbo kd vokcd dgy fevxobklsvsdsoc drkd kbo swzvowoxdon.
    %div.list--item
        = link_to "Go to Post overview", blogposts_path, class: "link green"

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Postforum
    %meta{:content => "width=device-width,initial-scale=1", :name => "viewport"}/
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = yield